name: Lighthouse Performance Testing
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.15.x

      # Set URLs based on context (simpler approach)
      - name: Set Lighthouse URLs
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For PR: Use Vercel preview URL pattern
            BRANCH_NAME="${{ github.head_ref }}"
            # Replace special characters and convert to lowercase for Vercel URL
            BRANCH_SLUG=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
            BASE_URL="https://lighthouse-test-git-${BRANCH_SLUG}-hayder86als-projects.vercel.app"
            echo "LIGHTHOUSE_URLS=${BASE_URL}/,${BASE_URL}/handla/mobiltelefoner,${BASE_URL}/support" >> $GITHUB_ENV
            echo "Testing deployment URL: ${BASE_URL}"
          else
            # For main branch: Use production URLs
            echo "LIGHTHOUSE_URLS=https://tre.se/,https://www.tre.se/handla/mobiltelefoner,https://www.tre.se/support" >> $GITHUB_ENV
            echo "Testing production URLs"
          fi

      - name: Run Lighthouse CI with Assertions
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: .lighthouseci/
