name: Lighthouse CI
on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/1 5-19 * * 1-5" # Runs every 1 min working days between 06:00 and 20:00 Swedish time
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://tre.se/
            https://www.tre.se/handla/mobiltelefoner
            https://www.tre.se/support
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
