name: Lighthouse Performance Testing
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.15.x

      # Set URLs based on context (simpler approach)
      - name: Set Lighthouse URLs
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For PR: Use a preview URL pattern (customize based on your deployment)
            PR_NUMBER=${{ github.event.number }}
            echo "LIGHTHOUSE_URLS=https://lighthouse-test-pr-${PR_NUMBER}.vercel.app/,https://lighthouse-test-pr-${PR_NUMBER}.vercel.app/handla/mobiltelefoner,https://lighthouse-test-pr-${PR_NUMBER}.vercel.app/support" >> $GITHUB_ENV
          else
            # For main branch: Use production URLs
            echo "LIGHTHOUSE_URLS=https://tre.se/,https://www.tre.se/handla/mobiltelefoner,https://www.tre.se/support" >> $GITHUB_ENV
          fi

      - name: Run Lighthouse CI with Assertions
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: .lighthouseci/
