name: Lighthouse Performance Testing
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  statuses: read
  checks: read

jobs:
  # Wait for Vercel deployment to complete
  wait-for-vercel:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      preview-url: ${{ steps.wait-for-vercel.outputs.url }}
    steps:
      - name: Wait for Vercel deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: wait-for-vercel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          check_interval: 5

  lighthouse:
    runs-on: ubuntu-latest
    needs: [wait-for-vercel]
    if: github.event_name == 'pull_request' && needs.wait-for-vercel.result == 'success' && needs.wait-for-vercel.outputs.preview-url != ''
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.15.x

      - name: Set Lighthouse URLs
        run: |
          # Use the actual Vercel preview URL from the previous job
          PREVIEW_URL="${{ needs.wait-for-vercel.outputs.preview-url }}"
          # Test both home page and support page
          echo "LIGHTHOUSE_URLS=${PREVIEW_URL},${PREVIEW_URL}/support" >> $GITHUB_ENV
          echo "Testing Vercel preview URLs:"
          echo "  - Home page: ${PREVIEW_URL}"
          echo "  - Support page: ${PREVIEW_URL}/support"

      - name: Run Lighthouse CI with Assertions
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: .lighthouseci/
